name: Build
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -o pipefail && xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -quiet -project Memories.xcodeproj -scheme Memories | xcpretty
  unit_tests:
    needs: build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -o pipefail && xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -project Memories.xcodeproj -scheme Memories -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' test | xcpretty
  ui_tests:
    needs: unit_tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -o pipefail && xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -project Memories.xcodeproj -scheme UITests -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' test | xcpretty
