name: Build
on:
  push:
    branches-ignore:
      - '!main'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: cd ./.github/scripts
    - run: ls -al
    - run: chmod=+x ./build.sh
    - run: ./build.sh
  unit_tests:
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Unit tests
      run: |
        cd ./.github/scripts
        chmod=+x ./unit_tests.sh
        ./unit_tests.sh
