name: Build
on:
  push:
    branches-ignore:
      - '!main'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: |
        xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -quiet -workspace Memories.xcworkspace -scheme iOS build | xcpretty
        cd /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T
        echo shaba1
        first=(*(N^/[1]))
        echo shaba2
        cat $first
  unit_tests:
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Unit tests
      run: |
        set -o pipefail && xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -workspace Memories.xcworkspace -scheme Memories -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' test | xcpretty
